version: '3'

tasks:
  build:
    cmds:
      - templ generate internal/view
      - task build-js
      - task build-css
      - go build -o ./bin/app cmd/main.go
  
  run:
    cmds:
      - task build
      - ./bin/app
  
  build-js:
    cmds:
      - npm --prefix ./web run build:js
  
  build-css:
    cmds:
      - npm --prefix ./web run build:css